// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import * as dotenv from "dotenv";

// Ensure DATABASE_URL from .env is available for `prisma db push`
dotenv.config();

const DATABASE_URL = process.env.DATABASE_URL!;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});


